spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securityJwt
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#Swagger/OpenAPI configuration
springdoc:
